apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:814rKw==,iv:2L7vdxY4XcWhhdMRQHwLt/nV0xOE7j6takNvSw/Rxqk=,tag:wUIxHr2Mmu+55DPoMbREyA==,type:str]
    userKey: ENC[AES256_GCM,data:Mb+SGg6O8Vfe/9v2vgaqRHq/h32qdG8cS+ylzLpwoent4RuWIrPBVYpZW5GSdtmTmdlfXddndX0=,iv:hl45YZuIiFODjzptuIBIzKNcd95GTu5ZgHuFf2CAf/s=,tag:/h5qU9t16TtXpMfFCgeKdA==,type:str]
kind: Secret
metadata:
    name: csi-rbd-secret
    namespace: ceph-csi-operator-system
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHbzRrdU03WjRyMVdwa0lZ
            TGNjRW5kYTd5YTBVNWJ5clZVb2UySGo3cm1rCk0yWGRRWUZlN2VSSGYzY0w2S0JY
            WGxHYzBtdVhYMDA3eGN4YlBCS2hWUEUKLS0tIERnb1BYQTNiZ3d2ZkFLTlRNZjFU
            VTR2S3dCd3hQUlIwVTdJUU1YNzQ4ZmcKhzwH008FSgeWXS7e45E3vapDMxRL+oMm
            CmYjlwsBOc6CYGErbhPyh1XBLCAC2vyuUAu9zZfkwjcp3FhBZYrEnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16jr9chq7kfpyg9da9gc0njmtqs7sgmrxmt99wlr3q7efg59xg9mqlq57rz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T16:57:06Z"
    mac: ENC[AES256_GCM,data:OQuimPWto8+WtLjvajNR10wxAv0aEHhPUCjj74U4uZ2U7ZbN5fM2Dad2FdY30RUEnAjwiwa1rJGqlf/TEg99QuIG5yDkUF62y7eCzVmxPzO+kS6ECOmrTTbifYXJFZazxPYdIg43cM+O2XwwhwS1+hyixlVGScg8TJszV8LEVvQ=,iv:taBEZrjhLxWj7BlShAClfD5Zviq/mDw6Hx/R6Xix8Gc=,tag:4N7M+rDUUvllr4ud+zsV5Q==,type:str]
    version: 3.13.3
