apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pricetracker-data
  namespace: pricetracker
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-rbd
  resources:
    requests:
      storage: 1Gi
