apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - adguard-exporter.yaml
  - adguardhome-sync.yaml
  - namespace.yaml
  - services.yaml
  - statefulsets.yaml
generators:
  - secret-generator.yaml
