apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc-backup.yaml
  - lmstudio-egress.yaml
  - openwebui.yaml
  - strata-egress.yaml
  - llmjp-proxy
generators:
  - secret-generator.yaml
