apiVersion: v1
data:
    openai-api-key: ENC[AES256_GCM,data:6l7Yb6vl3wsjKjmB,iv:CFs0+aaLhqVQGX40+bL9GKHE5xftJyTQoDr0jt8fxQY=,tag:x0KBFqWIGM2Cu0eJCt5mmg==,type:str]
    strata-api-key: ENC[AES256_GCM,data:NUcImeD7KF6jWtjz/EMfqTq6+S9x3QNFK+EV35TTZ0ldVFBL7gZaKi1gyq9Z1rplQ1wxJImejH9e9rzi,iv:NCcFI69vl1fg5SKy4y05wVUU0qjcfD1fKh4X5i1tWyc=,tag:ao547vjwDkZR5CQ55qCdrg==,type:str]
    webui-secret-key: ENC[AES256_GCM,data:dXVvh463M15E2nhPlyJ77T7dJ4b5zO/O5WVzbic/VYuQ8Go4gJKo+Ny+22xDSY5sj8CSoBTNuYijzBlN3d1FZ1VtrE6qXcqxQhc8MulHVsB944Q/Mlc6nw==,iv:O9qMSek08VM6Q/+xI1E1Kh/VvH7nzmuRzoZpJf0MYgY=,tag:pJkF3RumLJTaJB3AItKAWQ==,type:str]
kind: Secret
metadata:
    name: openwebui
    namespace: ai
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aDFTN3Znd1RydjZIU2Z3
            d2dCTHMvdWtGZ0ZSNmdqRWRuUnBUR2U4Q25jCnkxUDZTaFZ5YmdWbERnMTJFRlUv
            WGd6T3JFSmVMOVNLV0o0RGRGZmVjRzAKLS0tIEtyZWhGUEZkSDhlM080UkJhMHIv
            M2Z2NEJXclM5U3hUTGhzbTU5MTlyVzQKmVhcSQ+Kp95AzWNRSD8WNquoD9te7NMp
            iMvahF4a3WAqY4jWbSHKyn6SC4xg1LkVQTsI6lhDOM7Y2J00mR+FtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16jr9chq7kfpyg9da9gc0njmtqs7sgmrxmt99wlr3q7efg59xg9mqlq57rz
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-08T16:57:06Z"
    mac: ENC[AES256_GCM,data:Jh/sCZS8RnpZxakShG907tYMaIauPQxRGjlUQZM+xaePZD8DrIiWLkYblRyi0ZmjmoAq8fomx8pWRS8PVKOgJ9xNXoz6YnxN6C4fQOEyPs726x6E1KXs7tfjxU/nXxOYLS/UKzbOTohBwVRtjVFpdh6w84amP0NQ37Cl2bKffv4=,iv:+lInNRozCG+05W6+6/EkQUbHwG2ffUt2NR/qUse7rDY=,tag:mnUvSAKKxBQv+jPbsKojmg==,type:str]
    version: 3.13.3
