# metallb chart 0.16.1。frr-k8s モードなので FRR は frr-k8s サブチャートの DaemonSet にある
controller:
  resources:
    requests:
      cpu: 10m
      memory: 80Mi
    limits:
      memory: 160Mi
speaker:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      memory: 128Mi
frr-k8s:
  frrk8s:
    # controller コンテナと statuscleaner Deployment で共通
    resources:
      requests:
        cpu: 10m
        memory: 48Mi
      limits:
        memory: 128Mi
    frr:
      resources:
        requests:
          cpu: 10m
          memory: 48Mi
        limits:
          memory: 128Mi
    reloader:
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          memory: 96Mi
    frrMetrics:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 128Mi
    frrStatus:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 128Mi
