apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc-backup.yaml
  - dashboards.yaml
  - discord-bridge.yaml
  - hostapd-external.yaml
  - namespace.yaml
generators:
  - secret-generator.yaml
