# SOPS で暗号化した Secret を KSOPS で復号して生成する
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./discord-bridge-config.enc.yaml
  - ./grafana-admin.enc.yaml
  - ./ghcr-pull.enc.yaml
  - ./r2-backup.enc.yaml
