apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: netbox-db
  namespace: netbox
spec:
  instances: 2
  # 再起動を伴う変更では、primary をその場で再起動せずレプリカへ切り替える
  primaryUpdateMethod: switchover
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie
  affinity:
    podAntiAffinityType: preferred
  bootstrap:
    initdb:
      database: netbox
      owner: netbox
      encoding: UTF8
      localeCType: C
      localeCollate: C
  resources:
    requests:
      cpu: 50m
      memory: 144Mi
    limits:
      memory: 512Mi
  storage:
    storageClass: ceph-rbd
    size: 5Gi
  monitoring:
    enablePodMonitor: false
  plugins:
  - name: barman-cloud.cloudnative-pg.io
    enabled: true
    isWALArchiver: true
    parameters:
      barmanObjectName: r2
