apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backup-r2.yaml
  - pvc-backup.yaml
  - cluster-netbox-db.yaml
  - namespace.yaml
  - service-tailnet.yaml
  - valkey.yaml
generators:
  - secret-generator.yaml
