minecraft_rcon_password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKUjFhNWhFSStUU1RYN3ZV
            czFjUTJKQWZFb1JVdytXYlZqNlRiNDVUZmxNClJLQ2Y4cEhYNlprbjR5VGRvc1JI
            dm1Lc2N2Tmc2ZFd0WXJzSGFraUxsaUUKLS0tIDdaeGhtNXVvam51dEQ4TGNLYnBV
            TS9MNGE3bWRqcWcxOWU5ZnNQMkhza2sKm51gkJclkCT1zYwROAWajqK6vESzRjoJ
            eS0/R6h7I8pMx9VfMtcrtIXMfawSYNiYuOPIJ+L7uK2OWt8iKJiA2A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age16jr9chq7kfpyg9da9gc0njmtqs7sgmrxmt99wlr3q7efg59xg9mqlq57rz
    lastmodified: "2026-10-09T02:17:41Z"
    mac: ENC[AES256_GCM,data:YK+PSS5t3LWF0uBDmdBOiUvC20jqfeFYg0uBnj6BCBGclKN3mq6dsfupvVomWceNGwQmhts1rMVUlWlQag+sdzw6QvmGGSgoOmCh9te/mM79dCZh5uu0kwytEOV4T0AxPUac3Oh0DWVYxhCZumTtAZgsi9AkdIjoxalwmVqdVXg=,iv:dBO+grZt7rKikbGtiax2JSGlzXweQZbPzeo2khHt1Yk=,tag://2z9cpMqA6ClxDIUmMhbw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
