apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: lan-router
spec:
  exitNode: false
  proxyClass: default
  hostnamePrefix: lan-router
  replicas: 3
  subnetRouter:
    advertiseRoutes:
    - 192.168.1.0/24
  tags:
  - tag:k8s
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: egress-pg
spec:
  proxyClass: default
  replicas: 2
  type: egress
