# SOPS で暗号化した Secret を KSOPS で復号して生成する
apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
  - ./operator-oauth.enc.yaml
